config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  resources :projects
  resources :sessions

  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'fulltime', to: 'static_pages#fulltime'
  get 'contact', to: 'contacts#new'
  post 'contact', to: 'contacts#create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact
  include ActiveModel::Model
  attr_accessor :name, :email, :message
  validates_presence_of :name, :email, :message
end

app/models/project.rb
class Project < ApplicationRecord
  has_attached_file :homepage_image, styles: { large: "700x600>", medium: "400x300>" }
  has_attached_file :index_image, styles: { large: "700x600>", medium: "400x300>" }
  has_attached_file :image_3, styles: { large: "700x600>", medium: "400x300>" }
  has_attached_file :image_4, styles: { large: "700x600>", medium: "400x300>" }

  validates_presence_of :title, :description
  validates_attachment_content_type :homepage_image, content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"]
  validates_attachment_content_type :index_image, content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"]
  validates_attachment_content_type :image_3, content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"]
  validates_attachment_content_type :image_4, content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"]
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  private
    def logged_in?
      @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end

    helper_method :logged_in?
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(contact_params)

    if @contact.valid?
      ContactMailer.contact_me(@contact).deliver_now
      redirect_to root_path, notice: 'Message sent!'
    else
      redirect_to contact_path, alert: 'Something went wrong, please try again'
    end
  end

  private
    def contact_params
      params.require(:contact).permit(:name, :email, :message)
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  before_action :require_login, only: [:new, :create, :edit, :update, :destroy]

  def index
    @projects = Project.all
  end

  def show
  end

  def new
    @project = Project.new
  end

  def edit
  end

  def create
    @project = Project.new(project_params)

    if @project.save
      redirect_to projects_path, notice: 'Project was successfully created'
    else
      render action: 'new', alert: 'Something went wrong, try again'
    end
  end

  def update
    if @project.update(project_params)
      redirect_to @project, notice: 'Project was successfully updated.'
    else
      render action: 'edit', alert: 'Something went wrong, please try again'
    end
  end

  def destroy
    @project.destroy
    redirect_to projects_path
  end

  private

    def project_params
      params.require(:project).permit(:title, :description, :url, :github_repo, :homepage_image, :index_image, :image_3, :image_4)
    end

    def set_project
      @project = Project.find(params[:id])
    end

    def require_login
      redirect_to root_path, alert: 'You need to be logged in to do that' unless logged_in?
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url, notice: 'You are logged in'
    else
      redirect_to login_path, alert: 'Email or password is invalid'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: 'You are now Logged out'
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def fulltime
  end

  def home
    @projects = Project.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown(text)
    markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML,
      no_intra_emphasis: true,
      fenced_code_blocks: true,
      disable_indented_code_blocks: true)
    return markdown.render(text).html_safe
  end
end

app/helpers/project_helper.rb
module ProjectHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/contacts/_form.html.erb
  <%= form_with model: Contact.new, url: contact_path do |f| %>
    <%= f.text_field :name, placeholder: 'Name' %>
    <%= f.email_field :email, placeholder: 'Email' %>
    <%= f.text_area :message, placeholder: 'Message' %>
    <%= f.submit 'Send', class: 'send-button' %>
  <% end %>

app/views/contacts/new.html.erb
<div class="contact">
  <h1>Contact Me!</h1>
  
  <%= render 'form' %>
</div>

app/views/layouts/_footer.html.erb
<div class="footer">
  <hr>

  <div class="footer-components-wrapper">
    <div class="footer-components">
      &copy; <%= Time.now.year %> Kayla Howser
    </div>

    <div class="footer-components">
      Hang out with me on the internet:
    </div>

    <div class="footer-components">
      <a href="http://github.com/kaxla">Github</a> | <a href="http://linkedin.com/in/kaylahowser">LinkedIn</a>
    </div>
  </div>
</div>

app/views/layouts/_header.html.erb
<header>
  <div class="title-bar" data-responsive-toggle="header-menu" data-hide-for="medium">
    <button class="menu-icon" type="button" data-toggle></button>
    <div class="title-bar-title"></div>
  </div>

  <div class="top-bar" id="header-menu">
    <ul class="dropdown menu" data-dropdown-menu>
      <li <% if controller.controller_name == 'static_pages' %> class='active' <% end %>><%= link_to 'Home', root_path, target: '_blank' %></li>
      <li <% if controller.controller_name == 'welcome' %> class='active' <% end %>><%= link_to 'Resume', fulltime_path, target: '_blank' %></li>
      <li <% if controller.controller_name == 'projects' %> class='active' <% end %>><%= link_to 'Projects', projects_path, target: '_blank' %></li>
      <li <% if controller.controller_name == 'contacts' %> class='active' <% end %>><%= link_to 'Contact', contact_path, target: '_blank' %></li>
      <li><a href="https://medium.com/@kaylas.email.address" target="_blank">Blog</a></li>
      <li><a href="http://github.com/kaxla" target="_blank">Github</a></li>
      <li><a href="http://linkedin.com/in/kaylahowser" target="_blank">LinkedIn</a></li>
      <% if logged_in? %>
        <li>
          <%= link_to 'Log Out', logout_path %>
        </li>
      <% end %>
    </ul>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title><%= content_for?(:title) ? yield(:title) : "Kayla Howser" %></title>
    <link href="https://fonts.googleapis.com/css?family=Josefin+Sans|Karla|Mr+Bedfort" rel="stylesheet">
    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <% if controller.action_name != 'home' %>
      <%= render 'layouts/header' %>
    <% end %>

    <% if flash[:notice] %>
      <div class="callout secondary">
        <% flash.each do |key, value| %>
          <%= value %>
        <% end %>
      </div>
    <% end %>

    <% if flash[:alert] %>
      <div class="callout alert" >
        <% flash.each do |key, value| %>
          <%= value %>
        <% end %>
      </div>
    <% end %>

    <%= yield %>

    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :url %>
    <%= f.text_field :url %>
  </div>

  <div class="field">
    <%= f.label :github_repo %>
    <%= f.text_field :github_repo %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>


  <div>
    <%= f.label :homepage_image %>
    <%= f.file_field :homepage_image, class: "choose-file-button"%>
    <%= f.label :index_image %>
    <%= f.file_field :index_image, class: "choose-file-button"%>
    <%= f.file_field :image_3, class: "choose-file-button"%>
    <%= f.file_field :image_4, class: "choose-file-button"%>
  </div>

  <div class="actions">
    <%= f.submit class: "submit-button" %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<div class="project-form">
  <h1>Editing <%= @project.title %></h1>

  <%= render 'form' %>
</div>

app/views/projects/index.html.erb
<div class="project-index-header">
  My Projects
</div>

<div class="row small-up-1 medium-up-2 project-index-blocks">
  <% @projects.each do |project| %>
  <a href="<%= project_path(project.id) %>" class="column project-index">
    <div class="project-index-image hide-for-small-only">
      <%= image_tag project.index_image.url(:medium) %>
    </div>

    <div class="project-index-title">
      <%= project.title %>
    </div>
  </a>
  <% end %>
</div>

<div class="new-project-link-index">
  <% if logged_in? %>
    <%= link_to 'Create New Project', new_project_path, class: 'button' %>
  <% end %>
</div>

app/views/projects/new.html.erb
<div class="project-form">
  <h1>New Project</h1>

  <%= render 'form' %>
</div>

app/views/projects/show.html.erb
<div class="project-show-title">
  <%= @project.title %>
</div>

<div class="visit-site">
  <% if @project.url.present? %>
    <a href="<%= @project.url %>" class="button medium" target="_blank">
      <div class="project-link">
        Visit Live Site
      </div>
    </a>
  <% end %>

  <% if @project.github_repo.present? %>
    <a href="<%= @project.github_repo %>" class="button medium" target="_blank">
      <div class="project-link">
        Visit Github Repo
      </div>
    </a>
  <% end %>
</div>

<div class="project-show-description">
  <%= markdown(@project.description) %>
</div>

<div class="delete-edit">
  <% if logged_in? %>
    <%= link_to "Delete Project", project_path(@project), method: :delete, data: {confirm: "No, but really?"}, class: 'delete button' %>
    <%= link_to "Edit Project", edit_project_path(@project), class: "delete button" %>
  <% end %>
</div>

app/views/static_pages/fulltime.html.erb
<div class="fulltime-header">I'm Going Full-Time!</div>

<div class="fulltime-blurb">I've been freelancing for 3 years, but now I’m looking to bring
my unique understanding of customer needs and my passion for Fullstack
development to a full-time permanent, contract, or contract-to-hire role.
Ideally I would like to work remotely, but I'm also considering positions
in Seattle in the SODO, Pioneer Square, Downtown, or South Lake Union neighborhoods.</div>

<div class="fulltime-resume-wrapper">
  <img class="fulltime-resume" src="https://s3-us-west-2.amazonaws.com/kaylahowser2017portfolio/kayla-howser-resume.png" />
</div>


<a class="fulltime-link-wrapper" href="https://s3-us-west-2.amazonaws.com/kaylahowser2017portfolio/kayla-howser-resume.pdf" target="_blank">
  <div class="fulltime-link">
    Download a PDF of my Resume
  </div>
</a>

app/views/static_pages/home.html.erb
<div class="top-wrapper">
  <div class="name-wrapper">
    <div class="name">
      Kayla Howser
    </div>

    <div class="row align-center-middle">
      <div class="blurb small-12 medium-expand columns">
        Skilled full-stack Ruby developer with a knack for bringing tech to the non-technical
      </div>
    </div>
  </div>
</div>

<%= render 'layouts/header' %>

<div class="avatar">
  <img src="https://s3-us-west-2.amazonaws.com/kaylahowser2017portfolio/portfolio+bw+headshot.jpg" />
</div>

<div class="row align-center">
  <div class="long-blurb medium-10 columns">
    With a long-standing interest in web design and development, I built my first website on Angelfire in 2003.
    I worked in customer support for years but found myself at a crossroads with a strong desire to learn new things.
    I turned back to my passion for the web, this time in a professional setting. I’ve always been able to empathize
    and communicate effectively with customers and my relationship management skills have helped me thrive as a
    freelance developer.
  </div>
</div>

<hr>

<div class="row resume-contact-link-wrapper">
  <a class="medium-6 small-12 columns link-wrapper" href="/contact" target="_blank">
    <div class="link">
      Contact Me
    </div>
  </a>

  <a class="medium-6 small-12 columns link-wrapper" href="/fulltime" target="_blank">
    <div class="link">
      I'm going full time!
    </div>
  </a>
</div>

<hr>

<div class="home-projects-header">
  Projects
</div>

<div class="home-project-blocks">
  <% @projects.each do |project| %>
    <% if project.id.even? %>
    <!-- if the id is even put the image on the left -->
      <div class="project-wrapper">
        <a href="<%= project_path(project.id) %>" class="row project-link" target="_blank">
          <div class="hide-for-small-only large-6 column">
            <%= image_tag project.homepage_image.url, class: "project-image" %>
          </div>

          <div class="project-title large-6 column">
            <%= project.title %>
          </div>
        </a>
      </div>

    <% else %>
    <!-- if the id is odd put the image on the right -->
      <div class="project-wrapper">
        <a href="<%= project_path(project.id) %>" class="row project-link" target="blank">
          <div class="project-title large-6 column">
            <%= project.title %>
          </div>

          <div class="large-6 hide-for-small-only column">
            <%= image_tag project.homepage_image.url, class: "project-image" %>
          </div>
        </a>
      </div>
    <% end %>
  <% end %>
</div>

<script>
  $(document).ready(function() {
    function setHeight() {
      windowHeight = $(window).innerHeight();
      $('.top-wrapper').css('height', windowHeight);
    };
    setHeight();

    $(window).resize(function() {
      setHeight();
    });
  });
</script>